project_id = "eiuwenohohvmtbjcclpa"

[functions.plaid-create-link-token]
verify_jwt = false

[functions.plaid-exchange-token]
verify_jwt = false

[functions.plaid-get-transactions]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
